"""Seed Vietnamese food products for demo."""

from datetime import datetime, timezone

from app.core.database import SessionLocal
from app.models.product import DataSource, Product, ProductAdditive, ProductNutrient

SEED_PRODUCTS = [
    {
        "barcode": "8934564010014",
        "name": "Mì ăn liền Hảo Hảo vị Tôm chua cay",
        "brand": "Acecook",
        "category": "Instant noodles",
        "source": "manual",
        "source_url": "https://world.openfoodfacts.org/product/8934564010014",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột mì, dầu cọ, muối, đường, gia vị tôm, MSG (E621), chất bảo quản (E319)",
        "allergens": "gluten, crustaceans",
        "nutrients": {
            "energy_kcal": 450,
            "fat": 18,
            "saturated_fat": 8,
            "carbohydrates": 62,
            "sugars": 3,
            "proteins": 9,
            "salt": 3.5,
            "sodium": 1400,
            "fiber": 2,
        },
        "additives": [("E621", "Monosodium glutamate"), ("E319", "TBHQ")],
    },
    {
        "barcode": "8934564010021",
        "name": "Mì ăn liền Omachi sốt bò hầm",
        "brand": "Acecook",
        "category": "Instant noodles",
        "source": "manual",
        "source_url": "https://world.openfoodfacts.org/",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột mì, dầu cọ, muối, đường, bột bò, MSG (E621)",
        "allergens": "gluten",
        "nutrients": {
            "energy_kcal": 430,
            "fat": 16,
            "saturated_fat": 7,
            "carbohydrates": 60,
            "sugars": 4,
            "proteins": 10,
            "salt": 3.2,
            "sodium": 1280,
        },
        "additives": [("E621", "Monosodium glutamate")],
    },
    {
        "barcode": "8934564010038",
        "name": "Mì 3 Miền Gold tôm chua cay",
        "brand": "Masan",
        "category": "Instant noodles",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột mì, dầu, muối, gia vị, MSG",
        "nutrients": {"energy_kcal": 440, "fat": 17, "saturated_fat": 7.5, "carbohydrates": 61, "sugars": 3.5, "proteins": 9, "salt": 3.3, "sodium": 1320},
        "additives": [("E621", "MSG")],
    },
    {
        "barcode": "8934564010045",
        "name": "Mì Kokomi tôm chua cay",
        "brand": "Vifon",
        "category": "Instant noodles",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột mì, dầu cọ, muối, MSG",
        "nutrients": {"energy_kcal": 420, "fat": 15, "saturated_fat": 6.5, "carbohydrates": 58, "sugars": 3, "proteins": 8, "salt": 3.0, "sodium": 1200},
        "additives": [("E621", "MSG")],
    },
    {
        "barcode": "8934564010052",
        "name": "Mì Modern Lạnh Lắm",
        "brand": "Acecook",
        "category": "Instant noodles",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 4,
        "ingredients_text": "Bột mì, dầu, muối, gia vị",
        "nutrients": {"energy_kcal": 400, "fat": 14, "saturated_fat": 6, "carbohydrates": 55, "sugars": 2, "proteins": 9, "salt": 2.8, "sodium": 1120},
        "additives": [],
    },
    {
        "barcode": "8938503920012",
        "name": "Coca-Cola Original 330ml",
        "brand": "Coca-Cola",
        "category": "Soft drinks",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Nước, đường, CO2, caramel, acid citric, caffeine",
        "nutrients": {"energy_kcal": 42, "fat": 0, "saturated_fat": 0, "carbohydrates": 10.6, "sugars": 10.6, "proteins": 0, "salt": 0, "sodium": 5},
        "additives": [],
    },
    {
        "barcode": "8938503920029",
        "name": "Pepsi Cola 330ml",
        "brand": "PepsiCo",
        "category": "Soft drinks",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Nước, đường, CO2, acid citric",
        "nutrients": {"energy_kcal": 41, "fat": 0, "carbohydrates": 11, "sugars": 11, "proteins": 0, "sodium": 10},
        "additives": [],
    },
    {
        "barcode": "8938503920036",
        "name": "Sting Dâu 330ml",
        "brand": "SABECO",
        "category": "Energy drinks",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Nước, đường, acid citric, caffeine, taurine",
        "nutrients": {"energy_kcal": 45, "carbohydrates": 11, "sugars": 11, "sodium": 20},
        "additives": [],
    },
    {
        "barcode": "8938503920043",
        "name": "Number 1 Energy 330ml",
        "brand": "Tân Hiệp Phát",
        "category": "Energy drinks",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Nước, đường, caffeine, taurine, vitamin B",
        "nutrients": {"energy_kcal": 46, "carbohydrates": 11.5, "sugars": 11.5, "sodium": 15},
        "additives": [],
    },
    {
        "barcode": "8934564010100",
        "name": "Sữa tươi Vinamilk 100% 180ml",
        "brand": "Vinamilk",
        "category": "Milk",
        "source": "manual",
        "nutri_score": "b",
        "nova_group": 1,
        "ingredients_text": "Sữa tươi nguyên chất 100%",
        "nutrients": {"energy_kcal": 60, "fat": 3.2, "saturated_fat": 2, "carbohydrates": 4.5, "sugars": 4.5, "proteins": 3, "salt": 0.1, "sodium": 40, "fiber": 0},
        "additives": [],
    },
    {
        "barcode": "8934564010117",
        "name": "Sữa chua uống Vinamilk Probi",
        "brand": "Vinamilk",
        "category": "Yogurt drinks",
        "source": "manual",
        "nutri_score": "b",
        "nova_group": 3,
        "ingredients_text": "Sữa, đường, men vi sinh",
        "nutrients": {"energy_kcal": 75, "fat": 2, "saturated_fat": 1.2, "carbohydrates": 12, "sugars": 11, "proteins": 2.5, "sodium": 35},
        "additives": [],
    },
    {
        "barcode": "8934564010124",
        "name": "Sữa TH true MILK 180ml",
        "brand": "TH Group",
        "category": "Milk",
        "source": "manual",
        "nutri_score": "b",
        "nova_group": 1,
        "ingredients_text": "Sữa tươi nguyên chất",
        "nutrients": {"energy_kcal": 62, "fat": 3.5, "saturated_fat": 2.2, "carbohydrates": 4.2, "sugars": 4.2, "proteins": 3.1, "sodium": 38},
        "additives": [],
    },
    {
        "barcode": "8934564010131",
        "name": "Sữa đậu nành Fami 180ml",
        "brand": "Vinasoy",
        "category": "Soy milk",
        "source": "manual",
        "nutri_score": "a",
        "nova_group": 2,
        "ingredients_text": "Nước, đậu nành, đường, muối",
        "nutrients": {"energy_kcal": 55, "fat": 2, "saturated_fat": 0.3, "carbohydrates": 6, "sugars": 5, "proteins": 3.5, "sodium": 50, "fiber": 1},
        "additives": [],
    },
    {
        "barcode": "8934564010148",
        "name": "Bánh Oreo Original 137g",
        "brand": "Mondelez",
        "category": "Biscuits",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Bột mì, đường, dầu cọ, bột ca cao, muối",
        "allergens": "gluten, milk",
        "nutrients": {"energy_kcal": 480, "fat": 21, "saturated_fat": 7, "carbohydrates": 68, "sugars": 38, "proteins": 5, "salt": 0.8, "sodium": 320, "fiber": 2},
        "additives": [],
    },
    {
        "barcode": "8934564010155",
        "name": "Bánh quy Cosy Marie 336g",
        "brand": "Kinh Do",
        "category": "Biscuits",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột mì, đường, dầu thực vật, muối",
        "allergens": "gluten",
        "nutrients": {"energy_kcal": 460, "fat": 18, "saturated_fat": 8, "carbohydrates": 68, "sugars": 22, "proteins": 7, "salt": 1.2, "sodium": 480},
        "additives": [],
    },
    {
        "barcode": "8934564010162",
        "name": "Snack O'Star tôm cay 80g",
        "brand": "PepsiCo",
        "category": "Snacks",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột khoai tây, dầu, muối, gia vị tôm, MSG",
        "nutrients": {"energy_kcal": 520, "fat": 32, "saturated_fat": 10, "carbohydrates": 52, "sugars": 2, "proteins": 6, "salt": 2.5, "sodium": 1000},
        "additives": [("E621", "MSG")],
    },
    {
        "barcode": "8934564010179",
        "name": "Snack Poca khoai tây vị bò 54g",
        "brand": "Kinh Do",
        "category": "Snacks",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột khoai tây, dầu, muối, gia vị",
        "nutrients": {"energy_kcal": 510, "fat": 30, "saturated_fat": 9, "carbohydrates": 54, "sugars": 1.5, "proteins": 5, "salt": 2.2, "sodium": 880},
        "additives": [],
    },
    {
        "barcode": "8934564010186",
        "name": "Snack Lay's Classic 56g",
        "brand": "PepsiCo",
        "category": "Snacks",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Khoai tây, dầu hướng dương, muối",
        "nutrients": {"energy_kcal": 530, "fat": 33, "saturated_fat": 3, "carbohydrates": 53, "sugars": 0.5, "proteins": 6, "salt": 1.5, "sodium": 600},
        "additives": [],
    },
    {
        "barcode": "8934564010193",
        "name": "Mì gạo lứt Vifon 65g",
        "brand": "Vifon",
        "category": "Rice noodles",
        "source": "manual",
        "nutri_score": "b",
        "nova_group": 2,
        "ingredients_text": "Gạo lứt, muối",
        "nutrients": {"energy_kcal": 350, "fat": 1, "saturated_fat": 0.2, "carbohydrates": 78, "sugars": 0.5, "proteins": 7, "salt": 1.0, "sodium": 400, "fiber": 4},
        "additives": [],
    },
    {
        "barcode": "8934564010200",
        "name": "Yến mạch Quaker 500g",
        "brand": "Quaker",
        "category": "Cereals",
        "source": "manual",
        "nutri_score": "a",
        "nova_group": 1,
        "ingredients_text": "Yến mạch nguyên hạt 100%",
        "nutrients": {"energy_kcal": 370, "fat": 7, "saturated_fat": 1.2, "carbohydrates": 60, "sugars": 1, "proteins": 13, "salt": 0, "sodium": 2, "fiber": 10},
        "additives": [],
    },
    {
        "barcode": "8934564010217",
        "name": "Ngũ cốc Nestlé Koko Krunch 330g",
        "brand": "Nestlé",
        "category": "Cereals",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột mì, đường, bột ca cao, dầu cọ",
        "allergens": "gluten, milk",
        "nutrients": {"energy_kcal": 400, "fat": 8, "saturated_fat": 4, "carbohydrates": 72, "sugars": 28, "proteins": 7, "salt": 0.6, "sodium": 240, "fiber": 3},
        "additives": [],
    },
    {
        "barcode": "8934564010224",
        "name": "Nước mắm Nam Ngư 750ml",
        "brand": "Masan",
        "category": "Sauces",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 3,
        "ingredients_text": "Cá cơm, muối, đường",
        "nutrients": {"energy_kcal": 35, "fat": 0, "carbohydrates": 5, "sugars": 5, "proteins": 4, "salt": 18, "sodium": 7200},
        "additives": [],
    },
    {
        "barcode": "8934564010231",
        "name": "Tương ớt Chinsu 250g",
        "brand": "Masan",
        "category": "Sauces",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 3,
        "ingredients_text": "Ớt, đường, muối, tỏi",
        "nutrients": {"energy_kcal": 80, "fat": 0.5, "carbohydrates": 18, "sugars": 15, "proteins": 1, "salt": 5, "sodium": 2000},
        "additives": [],
    },
    {
        "barcode": "8934564010248",
        "name": "Mì trứng Vifon 200g",
        "brand": "Vifon",
        "category": "Dried noodles",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 2,
        "ingredients_text": "Bột mì, trứng, muối",
        "allergens": "gluten, eggs",
        "nutrients": {"energy_kcal": 360, "fat": 3, "saturated_fat": 1, "carbohydrates": 70, "sugars": 1, "proteins": 12, "salt": 1.5, "sodium": 600},
        "additives": [],
    },
    {
        "barcode": "8934564010255",
        "name": "Phô mai Laughing Cow 8v",
        "brand": "Bel",
        "category": "Cheese",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Sữa, muối, men vi sinh",
        "allergens": "milk",
        "nutrients": {"energy_kcal": 240, "fat": 20, "saturated_fat": 13, "carbohydrates": 3, "sugars": 3, "proteins": 12, "salt": 1.8, "sodium": 720},
        "additives": [],
    },
    {
        "barcode": "8934564010262",
        "name": "Bánh mì sandwich Wonder 400g",
        "brand": "Wonder",
        "category": "Bread",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 4,
        "ingredients_text": "Bột mì, nước, đường, men, muối",
        "allergens": "gluten",
        "nutrients": {"energy_kcal": 260, "fat": 3, "saturated_fat": 0.8, "carbohydrates": 48, "sugars": 5, "proteins": 8, "salt": 1.2, "sodium": 480, "fiber": 2},
        "additives": [],
    },
    {
        "barcode": "8934564010279",
        "name": "Trà xanh 0 độ Chanh 455ml",
        "brand": "Tân Hiệp Phát",
        "category": "Tea drinks",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 4,
        "ingredients_text": "Nước, đường, trà xanh, acid citric",
        "nutrients": {"energy_kcal": 35, "carbohydrates": 8.5, "sugars": 8.5, "sodium": 10},
        "additives": [],
    },
    {
        "barcode": "8934564010286",
        "name": "Trà Olong Tea+ 455ml",
        "brand": "SABECO",
        "category": "Tea drinks",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 4,
        "ingredients_text": "Nước, đường, trà olong",
        "nutrients": {"energy_kcal": 33, "carbohydrates": 8, "sugars": 8, "sodium": 8},
        "additives": [],
    },
    {
        "barcode": "8934564010293",
        "name": "Nước suối Lavie 500ml",
        "brand": "Lavie",
        "category": "Water",
        "source": "manual",
        "nutri_score": "a",
        "nova_group": 1,
        "ingredients_text": "Nước khoáng thiên nhiên",
        "nutrients": {"energy_kcal": 0, "fat": 0, "carbohydrates": 0, "sugars": 0, "proteins": 0, "salt": 0, "sodium": 5},
        "additives": [],
    },
    {
        "barcode": "8934564010300",
        "name": "Nước suối Aquafina 500ml",
        "brand": "PepsiCo",
        "category": "Water",
        "source": "manual",
        "nutri_score": "a",
        "nova_group": 1,
        "ingredients_text": "Nước tinh khiết",
        "nutrients": {"energy_kcal": 0, "fat": 0, "carbohydrates": 0, "sugars": 0, "proteins": 0, "sodium": 2},
        "additives": [],
    },
    {
        "barcode": "8934564010317",
        "name": "Sữa Ensure Gold 850g",
        "brand": "Abbott",
        "category": "Nutritional supplements",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 4,
        "ingredients_text": "Protein, đường, dầu, vitamin, khoáng chất",
        "nutrients": {"energy_kcal": 440, "fat": 14, "saturated_fat": 2, "carbohydrates": 55, "sugars": 20, "proteins": 18, "salt": 0.5, "sodium": 200, "fiber": 3},
        "additives": [],
    },
    {
        "barcode": "8934564010324",
        "name": "Bột giặt OMO Matic 2.7kg",
        "brand": "Unilever",
        "category": "Non-food",
        "source": "manual",
        "ingredients_text": "NOT FOOD - demo only",
        "nutrients": {},
        "additives": [],
    },
    {
        "barcode": "8934564010331",
        "name": "Kem Wall's Cornetto Socola",
        "brand": "Unilever",
        "category": "Ice cream",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Sữa, đường, socola, dầu cọ",
        "allergens": "milk",
        "nutrients": {"energy_kcal": 280, "fat": 15, "saturated_fat": 10, "carbohydrates": 32, "sugars": 26, "proteins": 4, "salt": 0.2, "sodium": 80},
        "additives": [],
    },
    {
        "barcode": "8934564010348",
        "name": "Chả lụa Viet Deli 200g",
        "brand": "Viet Deli",
        "category": "Processed meat",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Thịt heo, muối, đường, chất bảo quản (E250)",
        "nutrients": {"energy_kcal": 220, "fat": 12, "saturated_fat": 4, "carbohydrates": 5, "sugars": 3, "proteins": 22, "salt": 2.5, "sodium": 1000},
        "additives": [("E250", "Sodium nitrite")],
    },
    {
        "barcode": "8934564010355",
        "name": "Xúc xích CP Classic 500g",
        "brand": "CP",
        "category": "Processed meat",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Thịt gà, muối, đường, chất bảo quản (E250, E251)",
        "nutrients": {"energy_kcal": 250, "fat": 18, "saturated_fat": 6, "carbohydrates": 4, "sugars": 2, "proteins": 18, "salt": 2.8, "sodium": 1120},
        "additives": [("E250", "Sodium nitrite"), ("E251", "Sodium nitrate")],
    },
    {
        "barcode": "8934564010362",
        "name": "Gạo ST25 5kg",
        "brand": "Loc Troi",
        "category": "Rice",
        "source": "manual",
        "nutri_score": "a",
        "nova_group": 1,
        "ingredients_text": "Gạo ST25 nguyên hạt",
        "nutrients": {"energy_kcal": 350, "fat": 1, "saturated_fat": 0.2, "carbohydrates": 78, "sugars": 0, "proteins": 7, "salt": 0, "sodium": 1, "fiber": 1},
        "additives": [],
    },
    {
        "barcode": "8934564010379",
        "name": "Dầu ăn Neptune 1L",
        "brand": "Calofic",
        "category": "Cooking oil",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 2,
        "ingredients_text": "Dầu đậu nành tinh luyện",
        "nutrients": {"energy_kcal": 900, "fat": 100, "saturated_fat": 15, "carbohydrates": 0, "sugars": 0, "proteins": 0, "sodium": 0},
        "additives": [],
    },
    {
        "barcode": "8934564010386",
        "name": "Mật ong rừng U Minh 500ml",
        "brand": "U Minh",
        "category": "Honey",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 2,
        "ingredients_text": "Mật ong nguyên chất 100%",
        "nutrients": {"energy_kcal": 320, "fat": 0, "carbohydrates": 80, "sugars": 80, "proteins": 0.3, "sodium": 4},
        "additives": [],
    },
    {
        "barcode": "8934564010393",
        "name": "Sữa bột Dielac Alpha 900g",
        "brand": "Vinamilk",
        "category": "Baby formula",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 4,
        "ingredients_text": "Sữa bột, lactose, dầu thực vật, vitamin, khoáng chất",
        "nutrients": {"energy_kcal": 480, "fat": 22, "saturated_fat": 10, "carbohydrates": 55, "sugars": 45, "proteins": 12, "salt": 0.4, "sodium": 160},
        "additives": [],
    },
    {
        "barcode": "8934564010400",
        "name": "Bánh gạo One One vị tôm 150g",
        "brand": "Acecook",
        "category": "Rice crackers",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 4,
        "ingredients_text": "Gạo, dầu, muối, gia vị tôm",
        "nutrients": {"energy_kcal": 480, "fat": 20, "saturated_fat": 4, "carbohydrates": 68, "sugars": 2, "proteins": 6, "salt": 2.0, "sodium": 800},
        "additives": [],
    },
    {
        "barcode": "8934564010417",
        "name": "Kẹo Alpenliebe Sữa 32g",
        "brand": "Perfetti",
        "category": "Candy",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Đường, glucose syrup, sữa, dầu cọ",
        "allergens": "milk",
        "nutrients": {"energy_kcal": 420, "fat": 12, "saturated_fat": 8, "carbohydrates": 78, "sugars": 65, "proteins": 2, "salt": 0.2, "sodium": 80},
        "additives": [],
    },
    {
        "barcode": "8934564010424",
        "name": "Socola KitKat 4 thanh",
        "brand": "Nestlé",
        "category": "Chocolate",
        "source": "manual",
        "nutri_score": "e",
        "nova_group": 4,
        "ingredients_text": "Đường, bột mì, bơ ca cao, sữa",
        "allergens": "gluten, milk",
        "nutrients": {"energy_kcal": 520, "fat": 28, "saturated_fat": 16, "carbohydrates": 60, "sugars": 48, "proteins": 6, "salt": 0.3, "sodium": 120},
        "additives": [],
    },
    {
        "barcode": "8934564010431",
        "name": "Nước cam Tropicana 1L",
        "brand": "PepsiCo",
        "category": "Juice",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 3,
        "ingredients_text": "Nước cam ép, đường",
        "nutrients": {"energy_kcal": 45, "fat": 0, "carbohydrates": 11, "sugars": 10, "proteins": 0.5, "sodium": 5, "fiber": 0.5},
        "additives": [],
    },
    {
        "barcode": "8934564010448",
        "name": "Sữa chua TH true YOGURT",
        "brand": "TH Group",
        "category": "Yogurt",
        "source": "manual",
        "nutri_score": "b",
        "nova_group": 3,
        "ingredients_text": "Sữa, đường, men vi sinh",
        "nutrients": {"energy_kcal": 90, "fat": 3, "saturated_fat": 2, "carbohydrates": 12, "sugars": 11, "proteins": 3.5, "sodium": 45},
        "additives": [],
    },
    {
        "barcode": "8934564010455",
        "name": "Phở ăn liền Vifon 65g",
        "brand": "Vifon",
        "category": "Instant noodles",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 4,
        "ingredients_text": "Bột gạo, bột mì, muối, gia vị phở",
        "nutrients": {"energy_kcal": 380, "fat": 8, "saturated_fat": 3, "carbohydrates": 68, "sugars": 2, "proteins": 8, "salt": 2.5, "sodium": 1000},
        "additives": [],
    },
    {
        "barcode": "8934564010462",
        "name": "Mì lạnh Bibigo 163g",
        "brand": "CJ",
        "category": "Instant noodles",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột mì, dầu, muối, gia vị Hàn Quốc",
        "nutrients": {"energy_kcal": 410, "fat": 12, "saturated_fat": 4, "carbohydrates": 65, "sugars": 8, "proteins": 9, "salt": 2.8, "sodium": 1120},
        "additives": [],
    },
    {
        "barcode": "8934564010479",
        "name": "Nước ép Vfresh Cam 1L",
        "brand": "Vinamilk",
        "category": "Juice",
        "source": "manual",
        "nutri_score": "c",
        "nova_group": 3,
        "ingredients_text": "Nước cam ép từ concentrate, đường",
        "nutrients": {"energy_kcal": 48, "carbohydrates": 12, "sugars": 11, "sodium": 8, "fiber": 0.3},
        "additives": [],
    },
    {
        "barcode": "8934564010486",
        "name": "Bánh Pía Tân Huê Viên",
        "brand": "Tan Hue Vien",
        "category": "Pastry",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Bột mì, đường, dầu, trứng, đậu xanh",
        "allergens": "gluten, eggs",
        "nutrients": {"energy_kcal": 420, "fat": 18, "saturated_fat": 6, "carbohydrates": 58, "sugars": 25, "proteins": 6, "salt": 0.5, "sodium": 200},
        "additives": [],
    },
    {
        "barcode": "8934564010493",
        "name": "Cà phê G7 3in1",
        "brand": "Trung Nguyên",
        "category": "Coffee",
        "source": "manual",
        "nutri_score": "d",
        "nova_group": 4,
        "ingredients_text": "Cà phê, đường, bột sữa, chất tạo ngọt",
        "allergens": "milk",
        "nutrients": {"energy_kcal": 450, "fat": 14, "saturated_fat": 12, "carbohydrates": 72, "sugars": 45, "proteins": 4, "salt": 0.3, "sodium": 120},
        "additives": [],
    },
    {
        "barcode": "8934564010500",
        "name": "Cà phê đen Nespresso",
        "brand": "Nestlé",
        "category": "Coffee",
        "source": "manual",
        "nutri_score": "b",
        "nova_group": 2,
        "ingredients_text": "Hạt cà phê rang xay 100%",
        "nutrients": {"energy_kcal": 2, "fat": 0, "carbohydrates": 0.3, "sugars": 0, "proteins": 0.1, "sodium": 1},
        "additives": [],
    },
]


def seed():
    db = SessionLocal()
    try:
        sources = [
            DataSource(name="open_food_facts", url="https://world.openfoodfacts.org", license="ODbL"),
            DataSource(name="usda_fdc", url="https://fdc.nal.usda.gov", license="CC0"),
            DataSource(name="manual", url=None, license="Demo data"),
        ]
        for src in sources:
            existing = db.query(DataSource).filter(DataSource.name == src.name).first()
            if not existing:
                db.add(src)

        now = datetime.now(timezone.utc)
        for item in SEED_PRODUCTS:
            product = db.query(Product).filter(Product.barcode == item["barcode"]).first()
            if product:
                continue

            product = Product(
                barcode=item["barcode"],
                name=item["name"],
                brand=item.get("brand"),
                category=item.get("category"),
                source=item.get("source", "manual"),
                source_url=item.get("source_url"),
                ingredients_text=item.get("ingredients_text"),
                allergens=item.get("allergens"),
                nutri_score=item.get("nutri_score"),
                nova_group=item.get("nova_group"),
                last_synced_at=now,
            )
            db.add(product)
            db.flush()

            for code, amount in item.get("nutrients", {}).items():
                unit = "kcal" if code == "energy_kcal" else "g" if code != "sodium" else "mg"
                db.add(
                    ProductNutrient(
                        barcode=item["barcode"],
                        nutrient_code=code,
                        amount=float(amount),
                        unit=unit,
                        per_100g=True,
                    )
                )

            for e_num, e_name in item.get("additives", []):
                db.add(ProductAdditive(barcode=item["barcode"], e_number=e_num, name=e_name))

        db.commit()
        print(f"Seeded {len(SEED_PRODUCTS)} products")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
